server:
  port: 8081

spring:
  application:
    name: ms-pedido

  datasource:
    url: jdbc:postgresql://localhost:5432/pedidosdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: pedido-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# ------------------------
# Kafka Topics
# ------------------------
topics:
  pedido-criado: pedido.criado
  pagamento-processado: pagamento.processado

# ------------------------
# Logging
# ------------------------
logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    com.dogaohexa: DEBUG
